apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: internet
  namespace: openshift-ingress-operator
spec:
  domain: mydomain.it
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: Internal
  namespaceSelector:
    matchLabels:
      router: internet
  routeSelector:
      matchLabels:
        router: internet
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ''
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
  replicas: 2