kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    ingress.openshift.io/canary: canary_controller
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: ingress-canary
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          value: reserved
        - key: node-role.kubernetes.io/storage
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/builder