apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: .
helmCharts:
- name: helm-generated-base
  releaseName: helm-generated-base
  valuesFile: helm-generated-base/values.yaml