apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  finalizers:
    - dns.operator.openshift.io/dns-controller
  name: default
spec: {
  # COPY YAML FROM THE CLUSTER
}