apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    machineconfiguration.openshift.io/role: node-role
  name: base
spec: {}
