apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/machine-set

patches:
  - path: patches/machine-set-patch.yaml
    target:
      kind: MachineSet
      name: base
    options:
      allowNameChange: true