apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/infrastructure.yaml

patches:
  - path: patches/infrastructure-patch.yaml
    target:
      kind: Infrastructure
      name: cluster