apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace}}
{{- if .Values.labels }}
  labels: 
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
