apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: base
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  source: redhat-operators
  sourceNamespace: openshift-marketplace