apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/machine-set

nameSuffix: -compute-0

replacements:
- source:
    kind: MachineSet
    name: ocp-prod-x8h9t
    fieldPath: metadata.name
  targets:
  - select:
      kind: MachineSet
      name: ocp-prod-x8h9t
    fieldPaths:
    - spec.selector.matchLabels.machine\.openshift\.io/cluster-api-machineset
    - spec.template.metadata.labels.machine\.openshift\.io/cluster-api-machineset

patches:
  - path: patches/machine-set-patch.yaml
    target:
      kind: MachineSet
      name: ocp-prod-x8h9t